version: '3.8'

services:
  web:
    build: .
    depends_on:
      - redis-server
      - db
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - net
    volumes:
      - ./src/web_app:/app
    command: flask run --host=0.0.0.0

  redis-server:
    image: redis/redis-stack:latest
    networks:
      - net

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  pgdata:
